.gitlab-ci.yml: make sure all dtbs get built

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -165,6 +165,13 @@ build_linux:
       echo "cdns missing" >&2
       exit 1
     fi
+    for dtb in amlogic/meson-g12b-bananapi-cm4-mnt-pocket-reform.dtb freescale/imx8mp-mnt-pocket-reform.dtb freescale/imx8mq-mnt-reform2.dtb freescale/imx8mq-mnt-reform2-hdmi.dtb amlogic/meson-g12b-bananapi-cm4-mnt-reform2.dtb freescale/imx8mp-mnt-reform2.dtb freescale/fsl-ls1028a-mnt-reform2.dtb rockchip/rk3588-mnt-reform2.dtb; do
+      if ! dpkg-deb -c changes/linux-image-*-mnt-reform-arm64_*_arm64.deb | grep "/${dtb}\$"; then
+        echo "$dtb missing" >&2
+        exit 1
+      fi
+    done
+
   after_script: |
     echo "BASESUITE: $BASESUITE"
     echo "OURSUITE: $OURSUITE"
